# Exclude Airtable config from GitHub Secrets Scanning
# These values are not sensitive - they only identify a public read-only Airtable base
# The API key and base ID are required to be visible in the compiled JavaScript bundle
paths-ignore:
  - "src/config/airtable.ts"
